#!/usr/bin/env bash
#
# cut-doc-version.sh — Snapshot the current `docs/` tree into a versioned
# subfolder under `docs-versions/`, freezing it as <version>.
#
# Usage:
#   scripts/cut-doc-version.sh vX.Y
#
# This is the manual "release cut" step. Run it on the branch that will be
# tagged for release, just before creating the tag:
#
#   scripts/cut-doc-version.sh v0.2
#   git add docs-versions
#   git commit -m "Cut documentation version v0.2"
#   git tag -a v0.2.0 -m "Release v0.2.0"
#   git push --follow-tags
#
# Layout produced:
#   docs-versions/
#     versions.json                                       # ["v0.2","v0.1",…]
#     versioned_docs/version-v0.2/...                     # copy of docs/
#     versioned_sidebars/version-v0.2-sidebars.json       # autogen passthrough
#
# Why a separate `docs-versions/` folder instead of versioned_docs/ at repo
# root? Versioning artifacts are content, not infrastructure — grouping them
# under one parent keeps the repo root tidy. The hub's clone-spokes.sh
# symlinks the three files inside `docs-versions/` into the locations
# Docusaurus expects (site root, `<id>_`-prefixed when needed).
#
set -euo pipefail

VERSION="${1:-}"
if [[ -z "$VERSION" ]]; then
  echo "Usage: $0 VERSION_STRING (e.g. 2026.4)" >&2
  exit 1
fi


ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DOCS_DIR="$ROOT_DIR/docs"
VERSIONS_DIR="$ROOT_DIR/docs-versions"
VERSIONS_JSON="$VERSIONS_DIR/versions.json"
VERSIONED_DOCS="$VERSIONS_DIR/versioned_docs/version-$VERSION"
VERSIONED_SIDEBARS="$VERSIONS_DIR/versioned_sidebars"
SIDEBAR_FILE="$VERSIONED_SIDEBARS/version-$VERSION-sidebars.json"

if [[ ! -d "$DOCS_DIR" ]]; then
  echo "Error: $DOCS_DIR does not exist." >&2
  exit 1
fi

mkdir -p "$VERSIONS_DIR/versioned_docs" "$VERSIONED_SIDEBARS"

# versions.json holds the version names in newest-first order. Initialise
# with [] when missing so the rest of the script can treat it uniformly.
if [[ ! -f "$VERSIONS_JSON" ]]; then
  echo '[]' > "$VERSIONS_JSON"
fi

# Reject duplicates: cutting the same version twice silently would make the
# build emit a duplicate route and fail late.
if grep -q "\"$VERSION\"" "$VERSIONS_JSON"; then
  echo "Error: version $VERSION already present in $VERSIONS_JSON." >&2
  exit 1
fi
if [[ -d "$VERSIONED_DOCS" ]]; then
  echo "Error: $VERSIONED_DOCS already exists." >&2
  exit 1
fi

# Snapshot docs/ → versioned_docs/version-<v>/.
# Use cp -R (no -p) so timestamps reflect the cut, not the source files.
cp -R "$DOCS_DIR" "$VERSIONED_DOCS"

# Drop generated/non-versionable subtrees. `docs/samples/` is generated at
# hub build time by the genai-samples-docs-plugin from the spoke's current
# `samples/` tree; snapshotting it here would freeze stale import paths and
# couple a version's sample pages to whatever sample code happens to be at
# the spoke's HEAD at hub build time. Excluding samples from the snapshot
# means older versions simply omit that section until per-version samples
# are wired up properly.
rm -rf "$VERSIONED_DOCS/samples"

# Sidebar passthrough. The hub uses an autogenerated sidebar
# (sidebars/auto.ts) keyed by id `docs`, so the per-version sidebar JSON is
# just a passthrough to autogenerate against the versioned docs folder.
# Writing it explicitly satisfies docusaurus' versioning plugin which
# requires versioned_sidebars/version-<v>-sidebars.json to exist.
cat > "$SIDEBAR_FILE" <<'JSON'
{
  "docs": [
    {
      "type": "autogenerated",
      "dirName": "."
    }
  ]
}
JSON

# Prepend new version (newest first).
python3 - "$VERSIONS_JSON" "$VERSION" <<'PY'
import json, sys
path, version = sys.argv[1], sys.argv[2]
with open(path) as f:
    versions = json.load(f)
versions.insert(0, version)
with open(path, 'w') as f:
    json.dump(versions, f, indent=2)
    f.write('\n')
PY

echo "✓ Cut $VERSION"
echo "  versioned_docs:     ${VERSIONED_DOCS#"$ROOT_DIR/"}"
echo "  versioned_sidebars: ${SIDEBAR_FILE#"$ROOT_DIR/"}"
echo "  versions.json:      $(cat "$VERSIONS_JSON")"
