name: Release-please workflow

on:
  push:
    branches:
      - main

permissions: {} # No permissions by default on workflow level

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create releases and tags
      pull-requests: write # Needed to create release PRs
    steps:
      - name: Run release-please
        id: release-please
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json
          target-branch: main
